[tools]
usage = "latest"
node  = "24"
npm   = "11.7.0"
pnpm  = "10"
# flutter = "3.24"

[settings]
disable_tools = ["python"]

# [settings.node]
# mirror_url = "http://mirrors.cloud.tencent.com/npm/"
